2024-03-02 09:54:48,214 - __main__ - INFO - setData function - AQI is not an integer. Exception ValueError has occured for station=> nise gwal
2024-03-02 09:54:48,910 - __main__ - INFO - station=> Sector-51, Gurugram, result => ['103', 'Sector-51, Gurugram, India', Timestamp('2024-03-02 15:00:00')]
2024-03-02 09:54:48,910 - __main__ - INFO - The hourly data has been written to data/cron_job_data/sector_51_cron_output.csv with Timestamp: 2024-03-02 15:00:00
2024-03-02 09:54:49,591 - __main__ - INFO - station=> Sector-51, Gurugram, result => ['103', 'Sector-51, Gurugram, India', Timestamp('2024-03-02 15:00:00')]
2024-03-02 09:54:49,591 - __main__ - INFO - The hourly data has been written to static/data/sector_51_cron_output.csv with Timestamp: 2024-03-02 15:00:00
2024-03-02 09:54:50,292 - __main__ - INFO - station=> Teri Gram, result => ['173', 'Teri Gram, Gurugram, India', Timestamp('2024-03-02 15:00:00')]
2024-03-02 09:54:50,292 - __main__ - INFO - The hourly data has been written to data/cron_job_data/teri_gram_cron_output.csv with Timestamp: 2024-03-02 15:00:00
2024-03-02 09:54:50,988 - __main__ - INFO - station=> Vikas Sadan, result => ['114', 'Vikas Sadan Gurgaon, Gurgaon, India', Timestamp('2024-03-02 14:00:00')]
2024-03-02 09:54:50,988 - __main__ - INFO - The hourly data has been written to data/cron_job_data/vikas_sadan_cron_output.csv with Timestamp: 2024-03-02 14:00:00
2024-03-02 10:16:04,202 - __main__ - INFO - setData function - AQI is not an integer. Exception ValueError has occured for station=> nise gwal
