2024-02-08 00:27:55,529 - __main__ - INFO - station=> Sector-51, Gurugram, result => ['170', 'Sector-51, Gurugram, India', Timestamp('2024-02-08 05:00:00')]
2024-02-08 00:27:55,530 - __main__ - INFO - The hourly data has been written to data/cron_job_data/sector_51_cron_output.csv with Timestamp: 2024-02-08 05:00:00
2024-02-08 00:27:56,224 - __main__ - INFO - station=> Sector-51, Gurugram, result => ['170', 'Sector-51, Gurugram, India', Timestamp('2024-02-08 05:00:00')]
2024-02-08 00:27:56,224 - __main__ - INFO - The hourly data has been written to static/data/sector_51_cron_output.csv with Timestamp: 2024-02-08 05:00:00
2024-02-08 00:27:56,904 - __main__ - INFO - setData function - AQI is not an integer. Exception ValueError has occured for station=> Teri Gram
2024-02-08 00:27:57,583 - __main__ - INFO - station=> Vikas Sadan, result => ['147', 'Vikas Sadan Gurgaon, Gurgaon, India', Timestamp('2024-02-08 05:00:00')]
2024-02-08 00:27:57,583 - __main__ - INFO - The hourly data has been written to data/cron_job_data/vikas_sadan_cron_output.csv with Timestamp: 2024-02-08 05:00:00
