2024-02-21 01:13:41,117 - __main__ - INFO - setData function - AQI is not an integer. Exception ValueError has occured for station=> nise gwal
2024-02-21 01:13:41,589 - __main__ - INFO - station=> Sector-51, Gurugram, result => ['185', 'Sector-51, Gurugram, India', Timestamp('2024-02-21 06:00:00')]
2024-02-21 01:13:41,589 - __main__ - INFO - The hourly data has been written to data/cron_job_data/sector_51_cron_output.csv with Timestamp: 2024-02-21 06:00:00
2024-02-21 01:13:42,062 - __main__ - INFO - station=> Sector-51, Gurugram, result => ['185', 'Sector-51, Gurugram, India', Timestamp('2024-02-21 06:00:00')]
2024-02-21 01:13:42,062 - __main__ - INFO - The hourly data has been written to static/data/sector_51_cron_output.csv with Timestamp: 2024-02-21 06:00:00
2024-02-21 01:13:42,553 - __main__ - INFO - station=> Teri Gram, result => ['159', 'Teri Gram, Gurugram, India', Timestamp('2024-02-21 06:00:00')]
2024-02-21 01:13:42,553 - __main__ - INFO - The hourly data has been written to data/cron_job_data/teri_gram_cron_output.csv with Timestamp: 2024-02-21 06:00:00
2024-02-21 01:13:43,021 - __main__ - INFO - station=> Vikas Sadan, result => ['111', 'Vikas Sadan Gurgaon, Gurgaon, India', Timestamp('2024-02-21 06:00:00')]
2024-02-21 01:13:43,021 - __main__ - INFO - The hourly data has been written to data/cron_job_data/vikas_sadan_cron_output.csv with Timestamp: 2024-02-21 06:00:00
2024-02-21 01:13:43,021 - __main__ - INFO - Calling writeData & retrain_model functions.
2024-02-21 01:13:43,028 - __main__ - INFO - df_api columns Index(['AQI'], dtype='object')
2024-02-21 01:13:43,028 - __main__ - INFO - today=> 2024-02-21 & yesterday=> 2024-02-20
2024-02-21 01:13:43,030 - __main__ - INFO - temp_daily_aqi columns Index(['Unnamed: 0', 'Date', 'AQI'], dtype='object')
2024-02-21 01:13:43,032 - __main__ - INFO - temp_daily_aqi[2024-02-20]=> Empty DataFrame
Columns: [Unnamed: 0, AQI]
Index: []
2024-02-21 01:13:43,033 - __main__ - INFO - Index => 1447, yesterday => 2024-02-20 & AQI => 184.0
2024-02-21 01:13:43,033 - __main__ - INFO - Daily AQI data has been written to data/cleaned_data/Forecasting_time_series/sector_51_daily_aqi.csv
2024-02-21 01:13:43,033 - __main__ - INFO - Index => 1447, yesterday => 2024-02-20 & AQI => 184.0
2024-02-21 01:13:43,034 - __main__ - INFO - Daily AQI data has been written to static/data/sector_51_daily_aqi.csv
2024-02-21 01:13:43,038 - __main__ - INFO - Re-training the model & train_end is 2024-02-15 00:00:00
2024-02-21 01:13:44,105 - __main__ - INFO - Retrained the model & MAPE is 9.66%
2024-02-21 01:13:44,105 - __main__ - INFO - Retrained the model & MAE is 22.686153782735452%
2024-02-21 01:13:45,156 - __main__ - INFO - Forecast=> 2024-02-21    189.760434
2024-02-22    196.667017
2024-02-23    207.088128
2024-02-24    223.121772
2024-02-25    199.171464
Freq: D, Name: predicted_mean, dtype: float64
2024-02-21 01:13:45,156 - __main__ - INFO - The forecast data has been written to data/cleaned_data/Forecasting_time_series/forecast_sector_51_daily_aqi.csv
2024-02-21 01:13:45,157 - __main__ - INFO - The forecast data has been written to static/data/forecast_sector_51_daily_aqi.csv
2024-02-21 04:20:42,357 - __main__ - INFO - setData function - AQI is not an integer. Exception ValueError has occured for station=> nise gwal
2024-02-21 04:20:43,057 - __main__ - INFO - station=> Sector-51, Gurugram, result => ['189', 'Sector-51, Gurugram, India', Timestamp('2024-02-21 09:00:00')]
2024-02-21 04:20:43,057 - __main__ - INFO - The hourly data has been written to data/cron_job_data/sector_51_cron_output.csv with Timestamp: 2024-02-21 09:00:00
2024-02-21 04:20:43,755 - __main__ - INFO - station=> Sector-51, Gurugram, result => ['189', 'Sector-51, Gurugram, India', Timestamp('2024-02-21 09:00:00')]
2024-02-21 04:20:43,759 - __main__ - INFO - The hourly data has been written to static/data/sector_51_cron_output.csv with Timestamp: 2024-02-21 09:00:00
2024-02-21 04:20:44,442 - __main__ - INFO - station=> Teri Gram, result => ['157', 'Teri Gram, Gurugram, India', Timestamp('2024-02-21 09:00:00')]
2024-02-21 04:20:44,442 - __main__ - INFO - The hourly data has been written to data/cron_job_data/teri_gram_cron_output.csv with Timestamp: 2024-02-21 09:00:00
2024-02-21 04:20:45,139 - __main__ - INFO - station=> Vikas Sadan, result => ['86', 'Vikas Sadan Gurgaon, Gurgaon, India', Timestamp('2024-02-21 09:00:00')]
2024-02-21 04:20:45,139 - __main__ - INFO - The hourly data has been written to data/cron_job_data/vikas_sadan_cron_output.csv with Timestamp: 2024-02-21 09:00:00
2024-02-21 08:23:05,562 - __main__ - INFO - setData function - AQI is not an integer. Exception ValueError has occured for station=> nise gwal
2024-02-21 08:23:06,025 - __main__ - INFO - station=> Sector-51, Gurugram, result => ['185', 'Sector-51, Gurugram, India', Timestamp('2024-02-21 13:00:00')]
2024-02-21 08:23:06,025 - __main__ - INFO - The hourly data has been written to data/cron_job_data/sector_51_cron_output.csv with Timestamp: 2024-02-21 13:00:00
2024-02-21 08:23:06,490 - __main__ - INFO - station=> Sector-51, Gurugram, result => ['185', 'Sector-51, Gurugram, India', Timestamp('2024-02-21 13:00:00')]
2024-02-21 08:23:06,490 - __main__ - INFO - The hourly data has been written to static/data/sector_51_cron_output.csv with Timestamp: 2024-02-21 13:00:00
2024-02-21 08:23:06,956 - __main__ - INFO - station=> Teri Gram, result => ['173', 'Teri Gram, Gurugram, India', Timestamp('2024-02-21 13:00:00')]
2024-02-21 08:23:06,956 - __main__ - INFO - The hourly data has been written to data/cron_job_data/teri_gram_cron_output.csv with Timestamp: 2024-02-21 13:00:00
2024-02-21 08:23:07,420 - __main__ - INFO - station=> Vikas Sadan, result => ['100', 'Vikas Sadan Gurgaon, Gurgaon, India', Timestamp('2024-02-21 13:00:00')]
2024-02-21 08:23:07,421 - __main__ - INFO - The hourly data has been written to data/cron_job_data/vikas_sadan_cron_output.csv with Timestamp: 2024-02-21 13:00:00
2024-02-21 12:31:46,619 - __main__ - INFO - setData function - AQI is not an integer. Exception ValueError has occured for station=> nise gwal
2024-02-21 12:31:47,090 - __main__ - INFO - station=> Sector-51, Gurugram, result => ['165', 'Sector-51, Gurugram, India', Timestamp('2024-02-21 17:00:00')]
2024-02-21 12:31:47,090 - __main__ - INFO - The hourly data has been written to data/cron_job_data/sector_51_cron_output.csv with Timestamp: 2024-02-21 17:00:00
2024-02-21 12:31:47,565 - __main__ - INFO - station=> Sector-51, Gurugram, result => ['165', 'Sector-51, Gurugram, India', Timestamp('2024-02-21 17:00:00')]
2024-02-21 12:31:47,565 - __main__ - INFO - The hourly data has been written to static/data/sector_51_cron_output.csv with Timestamp: 2024-02-21 17:00:00
2024-02-21 12:31:48,041 - __main__ - INFO - station=> Teri Gram, result => ['167', 'Teri Gram, Gurugram, India', Timestamp('2024-02-21 17:00:00')]
2024-02-21 12:31:48,041 - __main__ - INFO - The hourly data has been written to data/cron_job_data/teri_gram_cron_output.csv with Timestamp: 2024-02-21 17:00:00
2024-02-21 12:31:48,513 - __main__ - INFO - station=> Vikas Sadan, result => ['84', 'Vikas Sadan Gurgaon, Gurgaon, India', Timestamp('2024-02-21 17:00:00')]
2024-02-21 12:31:48,513 - __main__ - INFO - The hourly data has been written to data/cron_job_data/vikas_sadan_cron_output.csv with Timestamp: 2024-02-21 17:00:00
2024-02-21 16:22:29,860 - __main__ - INFO - setData function - AQI is not an integer. Exception ValueError has occured for station=> nise gwal
2024-02-21 16:22:30,324 - __main__ - INFO - station=> Sector-51, Gurugram, result => ['167', 'Sector-51, Gurugram, India', Timestamp('2024-02-21 21:00:00')]
2024-02-21 16:22:30,324 - __main__ - INFO - The hourly data has been written to data/cron_job_data/sector_51_cron_output.csv with Timestamp: 2024-02-21 21:00:00
2024-02-21 16:22:30,785 - __main__ - INFO - station=> Sector-51, Gurugram, result => ['167', 'Sector-51, Gurugram, India', Timestamp('2024-02-21 21:00:00')]
2024-02-21 16:22:30,786 - __main__ - INFO - The hourly data has been written to static/data/sector_51_cron_output.csv with Timestamp: 2024-02-21 21:00:00
2024-02-21 16:22:31,254 - __main__ - INFO - station=> Teri Gram, result => ['159', 'Teri Gram, Gurugram, India', Timestamp('2024-02-21 21:00:00')]
2024-02-21 16:22:31,254 - __main__ - INFO - The hourly data has been written to data/cron_job_data/teri_gram_cron_output.csv with Timestamp: 2024-02-21 21:00:00
2024-02-21 16:22:31,717 - __main__ - INFO - station=> Vikas Sadan, result => ['75', 'Vikas Sadan Gurgaon, Gurgaon, India', Timestamp('2024-02-21 21:00:00')]
2024-02-21 16:22:31,717 - __main__ - INFO - The hourly data has been written to data/cron_job_data/vikas_sadan_cron_output.csv with Timestamp: 2024-02-21 21:00:00
2024-02-21 20:18:10,041 - __main__ - INFO - setData function - AQI is not an integer. Exception ValueError has occured for station=> nise gwal
2024-02-21 20:18:10,743 - __main__ - INFO - station=> Sector-51, Gurugram, result => ['163', 'Sector-51, Gurugram, India', Timestamp('2024-02-22 01:00:00')]
2024-02-21 20:18:10,743 - __main__ - INFO - The hourly data has been written to data/cron_job_data/sector_51_cron_output.csv with Timestamp: 2024-02-22 01:00:00
2024-02-21 20:18:11,421 - __main__ - INFO - station=> Sector-51, Gurugram, result => ['163', 'Sector-51, Gurugram, India', Timestamp('2024-02-22 01:00:00')]
2024-02-21 20:18:11,421 - __main__ - INFO - The hourly data has been written to static/data/sector_51_cron_output.csv with Timestamp: 2024-02-22 01:00:00
2024-02-21 20:18:12,098 - __main__ - INFO - station=> Teri Gram, result => ['144', 'Teri Gram, Gurugram, India', Timestamp('2024-02-22 01:00:00')]
2024-02-21 20:18:12,099 - __main__ - INFO - The hourly data has been written to data/cron_job_data/teri_gram_cron_output.csv with Timestamp: 2024-02-22 01:00:00
2024-02-21 20:18:12,772 - __main__ - INFO - station=> Vikas Sadan, result => ['79', 'Vikas Sadan Gurgaon, Gurgaon, India', Timestamp('2024-02-22 01:00:00')]
2024-02-21 20:18:12,772 - __main__ - INFO - The hourly data has been written to data/cron_job_data/vikas_sadan_cron_output.csv with Timestamp: 2024-02-22 01:00:00
